---
version: 2.1

orbs:
  steamcmd-test: jonakoudijs/steamcmd-test-orb@1.0.53

workflows:
  scheduled:
    jobs:
      - steamcmd-test/check:
          context: docker

          repo_slug:  "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
          image_slug: "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"

          app_id: 740

          filters:
            branches:
              only: master

  updated:
    jobs:
      - steamcmd-test/build:
          context: docker

          steamcmd_app_id: 740
          docker_image_slug: "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"

          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
