---
version: 2.1

orbs:
  steamcmd-test: jonakoudijs/steamcmd-test-orb@1.0.53

workflows:
  scheduled:
    jobs:
      - steamcmd-test/check:
          context: docker

          repo_slug: lanlords/steamcmd-test
          image_slug: lanlords/steamcmd-test
          app_id: 740

          filters:
            branches:
              only: master

  updated:
    jobs:
      - steamcmd-test/build:
          context: docker

          steamcmd_app_id: 740
          docker_image_slug: lanlords/steamcmd-test

          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
