---
version: 2.1

orbs:
  lanlords: lanlords/steamcmd-orb@1.0.1

workflows:
  scheduled:
    jobs:
      - lanlords/check:
          context: docker

          app_id: 740
          repo_slug:  "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
          image_slug: "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"

    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master

  updated:
    jobs:
      - lanlords/build:
          context: docker

          steamcmd_app_id: 740
          docker_image_slug: "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"

          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
