---
version: 2.1

orbs:
  lanlords-orb: jonakoudijs/steamcmd-test-orb@1.0.57

workflows:
  scheduled:
    jobs:
      - lanlords-orb/check:
          context: docker

          app_id: 740
          repo_slug:  "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
          image_slug: "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"

    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master

  updated:
    jobs:
      - lanlords-orb/build:
          context: docker

          steamcmd_app_id: 740
          docker_image_slug: "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"

          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
