---
version: 2.1

orbs:
  steamcmd-test: jonakoudijs/steamcmd-test-orb@1.0.49

workflows:
  scheduled:
    jobs:
      - steamcmd-test/check:
          repo_slug: lanlords/steamcmd-test
          image_slug: lanlords/steamcmd-test
          app_id: 740

          filters:
            branches:
              only: master

      - envtest:
          steps:
            - run:
                command: echo $DOCKER_USERNAME | cut -c 1-5

  updated:
    jobs:
      - steamcmd-test/build:
          steamcmd_app_id: 740
          docker_image_slug: lanlords/steamcmd-test

          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
