---
version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.1.0

jobs:
  reformat-version:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Reformat semver orb version
          command: echo "export SEMVER_TAG=$(echo $CIRCLE_PROJECT_REPONAME | cut -c 2-)" >> $BASH_ENV


workflows:
  publish:
    jobs:
      - orb-tools/lint
      - orb-tools/pack

      - reformat-version:
          steps:
            - run:
                name: test output
                command: |
                  echo "$CIRCLE_PROJECT_REPONAME" && \
                  echo "$SEMVER_TAG"
